// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// (regenerate with Rcpp::compileAttributes() after changing the C++ signatures)

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// integral2_est
SEXP integral2_est(arma::vec init_parameters, arma::vec time, arma::vec event, arma::vec IV, arma::vec IV_c, arma::mat Covariates, arma::mat D_status, arma::vec stime, int max_iter, double tol, double eta, double contraction);
RcppExport SEXP _DRIVE_integral2_est(SEXP init_parametersSEXP, SEXP timeSEXP, SEXP eventSEXP, SEXP IVSEXP, SEXP IV_cSEXP, SEXP CovariatesSEXP, SEXP D_statusSEXP, SEXP stimeSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP etaSEXP, SEXP contractionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type init_parameters(init_parametersSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time(timeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type event(eventSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type IV(IVSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type IV_c(IV_cSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Covariates(CovariatesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D_status(D_statusSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type stime(stimeSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type contraction(contractionSEXP);
    rcpp_result_gen = Rcpp::wrap(integral2_est(init_parameters, time, event, IV, IV_c, Covariates, D_status, stime, max_iter, tol, eta, contraction));
    return rcpp_result_gen;
END_RCPP
}
// integral_customized_est
SEXP integral_customized_est(double init_parameters, arma::vec time, arma::vec event, arma::vec IV, arma::vec IV_c, arma::mat ConfoundingPart, arma::mat D_status, arma::vec stime, int max_iter, double tol, double eta, double contraction);
RcppExport SEXP _DRIVE_integral_customized_est(SEXP init_parametersSEXP, SEXP timeSEXP, SEXP eventSEXP, SEXP IVSEXP, SEXP IV_cSEXP, SEXP ConfoundingPartSEXP, SEXP D_statusSEXP, SEXP stimeSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP etaSEXP, SEXP contractionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type init_parameters(init_parametersSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time(timeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type event(eventSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type IV(IVSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type IV_c(IV_cSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ConfoundingPart(ConfoundingPartSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D_status(D_statusSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type stime(stimeSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type contraction(contractionSEXP);
    rcpp_result_gen = Rcpp::wrap(integral_customized_est(init_parameters, time, event, IV, IV_c, ConfoundingPart, D_status, stime, max_iter, tol, eta, contraction));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DRIVE_integral2_est", (DL_FUNC) &_DRIVE_integral2_est, 12},
    {"_DRIVE_integral_customized_est", (DL_FUNC) &_DRIVE_integral_customized_est, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_DRIVE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
