#' Toy treatment-switching survival data
#'
#' A fully synthetic dataset of 200 subjects from the original linear,
#' scenario i (exogenous switching), generated by `SimulateData(N = 200,
#' seed = 2025)`. The true treatment effect is 0.1 and the administrative
#' follow-up limit is 5. No real patient data are included.
#'
#' @format A list with five components:
#' \describe{
#'   \item{Covariates}{A 200 by 2 numeric matrix of measured uniform covariates,
#'     named `X1` and `X2`. The simulated unmeasured confounder is omitted.}
#'   \item{Z}{Initial binary treatment assignment.}
#'   \item{W}{Switching time; `Inf` means the subject never switches. A finite
#'     time may occur after the end of observed follow-up.}
#'   \item{T_D_c}{Observed event or censoring time, at most 5.}
#'   \item{event}{Logical event indicator; `FALSE` denotes censoring.}
#' }
#' @source Generated from the simulation functions in DRIVE; see
#'   `data-raw/drive_toy.R` in the source repository for the regeneration script.
#' @examples
#' data(drive_toy)
#' head(drive_toy$Covariates)
#' fit <- TRTSWE(drive_toy, max_t = 5, methods = c("ITT", "recensor"))
#' fit
#' @seealso [SimulateData()], [New_SimuScenario()]
#' @md
"drive_toy"
