# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# (regenerate with Rcpp::compileAttributes() after changing the C++ signatures)

integral2_est <- function(init_parameters, time, event, IV, IV_c, Covariates, D_status, stime, max_iter, tol, eta, contraction) {
    .Call(`_DRIVE_integral2_est`, init_parameters, time, event, IV, IV_c, Covariates, D_status, stime, max_iter, tol, eta, contraction)
}

integral_customized_est <- function(init_parameters, time, event, IV, IV_c, ConfoundingPart, D_status, stime, max_iter, tol, eta, contraction) {
    .Call(`_DRIVE_integral_customized_est`, init_parameters, time, event, IV, IV_c, ConfoundingPart, D_status, stime, max_iter, tol, eta, contraction)
}
