# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

driv_cf_ml_est <- function(init_parameters, time, event, IV, IV_c, ConfoundingPart, D_status, stime, max_iter, tol, eta, contraction) {
    .Call(`_DRIVE_driv_cf_ml_est`, init_parameters, time, event, IV, IV_c, ConfoundingPart, D_status, stime, max_iter, tol, eta, contraction)
}

driv_s_est <- function(init_parameters, time, event, IV, IV_c, Covariates, D_status, stime, max_iter, tol, eta, contraction) {
    .Call(`_DRIVE_driv_s_est`, init_parameters, time, event, IV, IV_c, Covariates, D_status, stime, max_iter, tol, eta, contraction)
}

